name: "Release"

# Build the ente-io/ente's desktop/rc branch and create/update a draft release.
#
# For more details, see `docs/release.md` in ente-io/ente.

on:
    # Trigger manually or `gh workflow run desktop-release.yml`.
    workflow_dispatch:
    push:
        # Run when a tag matching the pattern "v*"" is pushed.
        #
        # See: [Note: Testing release workflows that are triggered by tags].
        tags:
            - "v*"

jobs:
    release:
        runs-on: ${{ matrix.os }}

        defaults:
            run:
                working-directory: desktop

        strategy:
            matrix:
                os: [windows-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  # Checkout the desktop/rc branch from the source repository.
                  repository: baddate/ente
                  ref: desktop/rc
                  submodules: recursive

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Increase yarn timeout
              # `yarn install` times out sometimes on the Windows runner,
              # resulting in flaky builds.
              run: yarn config set network-timeout 900000 -g

            - name: Install dependencies
              run: yarn install

            - name: Install libarchive-tools for pacman build
              if: startsWith(matrix.os, 'ubuntu')
              # See:
              # https://github.com/electron-userland/electron-builder/issues/4181
              run: sudo apt-get install libarchive-tools

            - name: Build
              uses: ente-io/action-electron-builder@v1.0.0
              with:
                  package_root: desktop
                  build_script_name: build:ci

                  # GitHub token, automatically provided to the action
                  # (No need to define this secret in the repo settings)
                  github_token: ${{ secrets.GITHUB_TOKEN }}

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # create a (draft) release after building. Otherwise upload
                  # assets to the existing draft named after the version.
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}

              env:
                  USE_HARD_LINKS: false
                  NEXT_PUBLIC_ENTE_ENDPOINT: https://ente.smj.im
